### ISSUE TITLE
The `--debug` flag doesn't show error in the validation module logs, it just hangs.

### ISSUE THREAD

**Issue by gabegma** [ServiceNow/azimuth#117]

**Comment by Dref360** [comment]
Funny enough, if we raise the `MultipleException` inside the Module instead of in the main thread it works as expected.
Should I make the change?

**Comment by gabegma** [comment]
Yes ok @Dref360! There are probably other issues hidden with the `--debug` flag, but at least it won't fail silently on the validation.

**Comment by gabegma** [comment]
Yes ok @Dref360! There are probably other issues hidden with the `--debug` flag, but at least it won't fail silently on the validation.
