### ISSUE TITLE
Add F1 Metric

### ISSUE THREAD

**Issue by gabegma** [ServiceNow/azimuth#124]

**Comment by Dref360** [comment]
Do we want this as default? Or simply better document how to add it?

**Comment by Dref360** [comment]
Unfortunatly it goes over in the table, but not in the exploration space.


![Image](https://user-images.githubusercontent.com/8976546/173390318-dfe8135d-2586-4ad0-acc8-2caa4357adae.png)



![Image](https://user-images.githubusercontent.com/8976546/173390464-f00986ab-fad8-4187-9e22-d377c7afdae8.png)

**Comment by gabegma** [comment]
I wonder if instead of the outcomes name in the table, we could use the icons (check mark and X with colors). We would gain so much space and it might be easier to understand at a glance. We can put the long name on hover. @JosephMarinier could that be feasible?

**Comment by Dref360** [comment]
Yup under `features/add_d1`

**Comment by JosephMarinier** [comment]
See #155

![Image](https://user-images.githubusercontent.com/8386369/174683094-19ab04fe-81d2-428c-8681-d0e7ea3bfcac.png)

**Comment by gabegma** [comment]
C

> Unfortunately, on a MacBook Pro 14, it makes the ECE overflow the metrics bar in the exploration space. I don't quite know what to do with that, yet. !

Can we put a simple horizontal scrollbar if it overflows?

**Comment by JosephMarinier** [comment]
There is a scrollbar. By default on Mac, it hides when it's not being used, hence why you don't see it on my previous screenshot.

![Image](https://user-images.githubusercontent.com/8386369/174816659-5154f778-1cd0-4a01-8d77-e2ceec2374fa.png)

**Comment by gabegma** [comment]
Ah perfect - that LGTM for now!
