### ISSUE TITLE
Can we order rows/columns in the confusion matrix in terms of meaningful confusion clusters.

### ISSUE THREAD

**Issue by gabegma** [ServiceNow/azimuth#140]

**Comment by Dref360** [comment]
Example using Cuthill-Mckee algorithm. I put a threshold at .05, it seems to help.

```python
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import reverse_cuthill_mckee

graph = csr_matrix(DATA > 0.05)
output = reverse_cuthill_mckee(graph, symmetric_mode=False)
print(output)
```

![image](https://user-images.githubusercontent.com/8976546/174348671-dd4b705a-19ca-41be-bd25-2735cdaa3b1f.png)

![image](https://user-images.githubusercontent.com/8976546/174348717-b1380365-a0aa-4681-a1c6-24aa37de2475.png)
