### ISSUE TITLE
Fix URLs to docs

### ISSUE THREAD

**Issue by JosephMarinier** [ServiceNow/azimuth#152]
This is following the versioning of our documentation.

URLs without the version (for example https://servicenow.github.io/azimuth/getting-started that is linked in the README) still exist and seem to point to an older version (not main). I can imagine a couple of options:

1. Those URLs could redirect to /main/... ?
2. Those URLs could be the "main" ones? Replacing /main/...
3. Those URLs could die? And we make sure we convert all the links to them.

**Comment by JosephMarinier** [comment]
Option 1 with 5484db5c28e315126aa87ea122e1a8d489f839aa and deleting all the files from the "root" version of the docs.

**Comment by Dref360** [comment]
When I click on v2.1, the versioning disappear.
https://servicenow.github.io/azimuth/v2.1/

**Comment by JosephMarinier** [comment]
I reopened the issue since I found a bug with my current implementation is that if you visit `/main/potato`, you get redirected to `/main/main/potato`, then to `/main/main/main/potato` and so on and so forth.
