### ISSUE TITLE
Web app no longer loading when there is no pipeline

### ISSUE THREAD

**Issue by gabegma** [ServiceNow/azimuth#331]
The web app no longer loads when there is no pipeline. It can be reproduced using `make CFG_PATH=local_configs/development/clinc_dummy/conf_no_model.json launch.local`, 

![Image](https://user-images.githubusercontent.com/36087158/206348760-57cd81e5-9637-4af4-bc44-8a7dd2086ce6.png)

**Comment by JosephMarinier** [comment]
Very good catch Gab! Thank you!
