### ISSUE TITLE
Keep GPU workload to one worker locally.

### ISSUE THREAD

**Issue by Dref360** [ServiceNow/azimuth#411]
**Is your feature request related to a problem? Please describe.**
I have a very small GPU (6Gb), so even with a batch size of 1, I can't run Azimuth with saliency on my computer. Both Dask workers load the model on the GPU which creates a OOM.

**Describe the solution you'd like**
When using a local Dask cluster (the default), it would be great if we assigned resources to one of them so that it handles all GPU-related tasks.

**Describe alternatives you've considered**
I could run on CPU, but that takes a while.

**Additional context**

**Comment by gabegma** [comment]
Thanks for filling the issue @Dref360! We'll take a look in a coming weeks.
