### ISSUE TITLE
Tensor size mismatch with HF pipeline

### ISSUE THREAD

**Issue by vilhub** [ServiceNow/azimuth#439]
Hi,

I'm eager to try Azimuth as the tool looks great, however I've been running into some issues setting it up. I'm trying to run Azimuth with a simple HF binary classification pipeline. My data contains very long texts and causes errors when I try to run Azimuth with it, I get
```
backend_1  | azimuth.utils.logs.MultipleExceptions: We found the following exceptions:  
backend_1  | 	The expanded size of the tensor (972) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [10, 972].  Tensor sizes: [1, 514]
```

I started with the setup indicated in the "Run on your use case" of the getting started guide which did not work for me and then tried to switch to a custom load_pipeline function, but I didn't find a way to fix padding and truncation settings at pipeline definition time. This can be done when calling the inference pipeline but not at definition time as far as I know.

So now I didn't find a way to define a custom caller to the inference pipeline, but I feel like I'm missing something where I could have fed  `truncate=True` instead of jumping through the hoops of redefining everything?

Any pointers would be appreciated.

Best,
Vil

**Comment by gabegma** [comment]
Hi @vilhub! Thank you for your interest in Azimuth! You are absolutely right, you should not have to redefine anything, we just didn't handle long utterances yet. We'll add `truncate=True` and do a patch version after so you can try it. @Dref360 I think you already have that locally?

Also, if you have slack, don't hesitate to join our [slack](https://join.slack.com/t/azimuth-org/shared_invite/zt-1i9eu48n9-7NnCXHw5VzUs~gs20xHxyg) if you want to further chat and debug in a more interactive way.

**Comment by vilhub** [comment]
Hi @gabegma , that was a very quick resolution, thanks so much! I'll test it out soon and let you know how it goes. Many thanks!

**Comment by gabegma** [comment]
Awesome, we just released the fix in v.2.5.3. Assuming no problem in the build, it should be available in an hour or so. Let us know if you still face the issue (or another!)
