### ISSUE TITLE
clear steps to run without docker?

### ISSUE THREAD

**Issue by zia-hasan** [ServiceNow/azimuth#44]
**Describe the solution you'd like**
Could you provide a solution to run this without using docker? Although it is mentioned in the tutorial that it can be run without docker and we could use poetry. However, after following through the first few steps in the tutorial there were `make` commands which started building some large docker images. Docker images take a long time to build, eat a lot of resources and seem like overkill. If I just would like to play with the package, it seems not easy without committing resources and time.

**Comment by Dref360** [comment]
Right we could make it clearer thank you for raising this issue.

When the backend and frontend are both installed, the following steps can be run without docker.

```
make local_configs  # generate configs
make CFG_PATH={path to config file} launch.local # Start the backend

# In another terminal
cd webapp && yarn start # Starts the frontend.
```

**Comment by gabegma** [comment]
Hi Zia - I put a PR up to clarify the instructions! Feel free to comment directly in the PR. #50
