### ISSUE TITLE
Improving the section "Prepare the Config"

### ISSUE THREAD

**Issue by zia-hasan** [ServiceNow/azimuth#51]
**Describe the solution you'd like**
In "**Run on your use case**" doc and under  "**1. Prepare the Config File**" section, step 2 is quite confusing. The repository itself is called `azimuth` and then there is also an `azimuth` folder within it. So when the doc says in `azimuth/config` copy `config/examples/clinc_oos/conf.json`, I suppose it meant `config` folder at the repository root but I had to look inside `azimuth/azimuth` folder. There needs to be a little improvement for this step description.

**Additional context**
I don't understand the context fully but could there be more intuitive names for folders `azimuth_shr` and `azimuth`? Not sure what `shr` stands for and why there is `azimuth` within `azimuth` 🙂. Not asking to change it but just sharing my general confusion while browsing the repository 👀.

**Comment by gabegma** [comment]
Hi Zia, great questions again. The confusion is very understandable, and partially comes from the fact that soon, our users won't need to clone our repo to run Azimuth; we will do releases that will be available on Docker Hub, and users will no longer see locally all of our folders (including `azimuth/azimuth`, which contains the back end).  Our instructions were written with that in mind, but unfortunately, we are not yet set up on Docker Hub (coming soon!).

I will improve the documentation further to explain this better, thanks for pointing out those confusing instructions!

**Comment by gabegma** [comment]
Don't hesitate to open this again @zia-hasan if you think my latest PR is not addressing your issue sufficiently!
