### ISSUE TITLE
Auto selection of the saliency layer

### ISSUE THREAD

**Issue by Dref360** [ServiceNow/azimuth#582]
Hello!

I recently come around [`model.base_model.get_input_embeddings()`](https://huggingface.co/docs/transformers/main/en/main_classes/model#transformers.PreTrainedModel.get_input_embeddings), a method implemented by Huggingface models to get the `Embedding` layer. I was wondering if we could add an "auto" setting to the saliency layer so that I don't have to look for this layer in my architecture.

### Proposed changes:

```python
# my_config.json
{
...
"saliency_layer": "auto"
...
}
```

```python
class ModelContractConfig:
    saliency_layer: Literal['auto'] | None | str = None
```

**Comment by gabegma** [comment]
Hey Fred! Great find, we should totally implement that! I'm on it.

**Comment by gabegma** [comment]
This also allows for every pipeline to have its own saliency layer - a problem that we found recently @JosephMarinier
