### ISSUE TITLE
Use model's own embedding to compute similarity smart tags.

### ISSUE THREAD

**Issue by Dref360** [ServiceNow/azimuth#603]
Hello!

It would be useful to me if I could use the model's own embedding to compute similarity smart tags. For my particular use case, semantic embeddings are not useful.

### Proposal

config.json
```json
{
	"similarity" : {"faiss_encoder": "model" } // could be 'self-similar'? 
}
```

One can get the embedding of their HuggingFace model with:

```python
inputs = tokenizer(...)
model : BertModelForSequenceClassification = ...
embedding = model.base_model(**inputs).last_hidden_state[:, 0, :] # Take first token embedding
```

A simpler approach is to load the same model with the `feature-extractor` task, but that might be more involved.

`pipe = pipeline('feature-extraction', model='your_model', truncation=True)`

EDIT: One can also do

```python
pipe2 = pipeline('feature-extraction', model=pipe.model.base_model, tokenizer=pipe.tokenizer)
``` where pipe is the initial PipelineForSequenceClassification.

**Comment by gabegma** [comment]
Hey @Dref360 - that's a great suggestion, we've had this request a few times. We'll aim to prioritize that in the coming weeks.

**Comment by Dref360** [comment]
I didn't realize that sentence-transformer can now load model directly from the hub and convert them. The only caveat is that it uses mean pooling instead of the first token. Not a terrible issue AFAIK.

Closing!
