### ISSUE TITLE
Visual indicator of how similar utterances are in the similar utterances tab

### ISSUE THREAD

**Issue by gabegma** [ServiceNow/azimuth#95]
Bars? With different colors when the similarity is above or below the threshold (0.5) that determine the `no_close` smart tag?

**Comment by nandhinibsn** [comment]
Added screenshot of the change
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/103529971/180502459-f72c7e6f-52c5-4e27-9e22-716663466dbb.png">
